/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_newline = 1,
  anon_sym_ATpage = 2,
  anon_sym_ATusing = 3,
  anon_sym_ATinject = 4,
  anon_sym_ATlayout = 5,
  anon_sym_ATinherits = 6,
  anon_sym_ATattribute = 7,
  sym_directive_value = 8,
  anon_sym_DQUOTE = 9,
  sym_quoted_value_content = 10,
  anon_sym_ATcode = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  sym_csharp_text = 14,
  anon_sym_LT = 15,
  anon_sym_GT = 16,
  anon_sym_SLASH_GT = 17,
  anon_sym_LT_SLASH = 18,
  sym_tag_name = 19,
  anon_sym_EQ = 20,
  sym_attribute_name = 21,
  sym_unquoted_value = 22,
  anon_sym_AT = 23,
  sym_identifier = 24,
  sym_text = 25,
  sym_source_file = 26,
  sym_directive = 27,
  sym_quoted_value = 28,
  sym_code_block = 29,
  sym_csharp_code = 30,
  sym_csharp_block = 31,
  sym_markup_element = 32,
  sym_self_closing_markup_element = 33,
  sym_tag_open = 34,
  sym_self_closing_tag_open = 35,
  sym_tag_close = 36,
  sym_attribute = 37,
  sym_razor_expression = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_csharp_code_repeat1 = 40,
  aux_sym_markup_element_repeat1 = 41,
  aux_sym_tag_open_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_newline] = "newline",
  [anon_sym_ATpage] = "@page",
  [anon_sym_ATusing] = "@using",
  [anon_sym_ATinject] = "@inject",
  [anon_sym_ATlayout] = "@layout",
  [anon_sym_ATinherits] = "@inherits",
  [anon_sym_ATattribute] = "@attribute",
  [sym_directive_value] = "directive_value",
  [anon_sym_DQUOTE] = "\"",
  [sym_quoted_value_content] = "quoted_value_content",
  [anon_sym_ATcode] = "@code",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_csharp_text] = "csharp_text",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_unquoted_value] = "unquoted_value",
  [anon_sym_AT] = "@",
  [sym_identifier] = "identifier",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_directive] = "directive",
  [sym_quoted_value] = "quoted_value",
  [sym_code_block] = "code_block",
  [sym_csharp_code] = "csharp_code",
  [sym_csharp_block] = "csharp_block",
  [sym_markup_element] = "markup_element",
  [sym_self_closing_markup_element] = "self_closing_markup_element",
  [sym_tag_open] = "tag_open",
  [sym_self_closing_tag_open] = "self_closing_tag_open",
  [sym_tag_close] = "tag_close",
  [sym_attribute] = "attribute",
  [sym_razor_expression] = "razor_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_csharp_code_repeat1] = "csharp_code_repeat1",
  [aux_sym_markup_element_repeat1] = "markup_element_repeat1",
  [aux_sym_tag_open_repeat1] = "tag_open_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_newline] = sym_newline,
  [anon_sym_ATpage] = anon_sym_ATpage,
  [anon_sym_ATusing] = anon_sym_ATusing,
  [anon_sym_ATinject] = anon_sym_ATinject,
  [anon_sym_ATlayout] = anon_sym_ATlayout,
  [anon_sym_ATinherits] = anon_sym_ATinherits,
  [anon_sym_ATattribute] = anon_sym_ATattribute,
  [sym_directive_value] = sym_directive_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_quoted_value_content] = sym_quoted_value_content,
  [anon_sym_ATcode] = anon_sym_ATcode,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_csharp_text] = sym_csharp_text,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_unquoted_value] = sym_unquoted_value,
  [anon_sym_AT] = anon_sym_AT,
  [sym_identifier] = sym_identifier,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_directive] = sym_directive,
  [sym_quoted_value] = sym_quoted_value,
  [sym_code_block] = sym_code_block,
  [sym_csharp_code] = sym_csharp_code,
  [sym_csharp_block] = sym_csharp_block,
  [sym_markup_element] = sym_markup_element,
  [sym_self_closing_markup_element] = sym_self_closing_markup_element,
  [sym_tag_open] = sym_tag_open,
  [sym_self_closing_tag_open] = sym_self_closing_tag_open,
  [sym_tag_close] = sym_tag_close,
  [sym_attribute] = sym_attribute,
  [sym_razor_expression] = sym_razor_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_csharp_code_repeat1] = aux_sym_csharp_code_repeat1,
  [aux_sym_markup_element_repeat1] = aux_sym_markup_element_repeat1,
  [aux_sym_tag_open_repeat1] = aux_sym_tag_open_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATpage] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATusing] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATinject] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATlayout] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATinherits] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATattribute] = {
    .visible = true,
    .named = false,
  },
  [sym_directive_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_value_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATcode] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_csharp_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [sym_csharp_code] = {
    .visible = true,
    .named = true,
  },
  [sym_csharp_block] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_element] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_markup_element] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_open] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag_open] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_close] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_razor_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_csharp_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markup_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_open_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_close = 2,
  field_content = 3,
  field_name = 4,
  field_open = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_close] = "close",
  [field_content] = "content",
  [field_name] = "name",
  [field_open] = "open",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_open, 0},
  [1] =
    {field_value, 1},
  [2] =
    {field_name, 1},
  [3] =
    {field_close, 1},
    {field_open, 0},
  [5] =
    {field_name, 0},
  [6] =
    {field_close, 2},
    {field_open, 0},
  [8] =
    {field_content, 1},
  [9] =
    {field_body, 2},
  [10] =
    {field_name, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 4,
  [18] = 18,
  [19] = 8,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 9,
  [27] = 27,
  [28] = 28,
  [29] = 6,
  [30] = 7,
  [31] = 31,
  [32] = 12,
  [33] = 14,
  [34] = 34,
  [35] = 15,
  [36] = 16,
  [37] = 37,
  [38] = 34,
  [39] = 37,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 10,
  [46] = 13,
  [47] = 47,
  [48] = 48,
  [49] = 47,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 54,
  [57] = 57,
  [58] = 58,
  [59] = 55,
  [60] = 60,
  [61] = 52,
  [62] = 53,
  [63] = 60,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '\n', 46,
        '"', 55,
        '/', 106,
        '<', 71,
        '=', 106,
        '>', 65,
        '@', 72,
        '_', 104,
        '{', 106,
        '}', 106,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'') ADVANCE(106);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '<') ADVANCE(64);
      if (lookahead == '@') ADVANCE(107);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(111);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '=') ADVANCE(69);
      if (lookahead == '>') ADVANCE(65);
      if (lookahead == '@') ADVANCE(43);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '}') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(66);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'b') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(48);
      END_STATE();
    case 17:
      if (lookahead == 'g') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == 'h') ADVANCE(15);
      if (lookahead == 'j') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 38:
      if (lookahead == 'y') ADVANCE(25);
      END_STATE();
    case 39:
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '}') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 40:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 41:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 42:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 43:
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '<') ADVANCE(63);
      if (lookahead == '@') ADVANCE(108);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_ATpage);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_ATusing);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_ATinject);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_ATlayout);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_ATinherits);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_ATattribute);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_directive_value);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_directive_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_quoted_value_content);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_quoted_value_content);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_ATcode);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_csharp_text);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead == '}') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_csharp_text);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == '/') ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'a') ADVANCE(98);
      if (lookahead == 'c') ADVANCE(89);
      if (lookahead == 'i') ADVANCE(87);
      if (lookahead == 'l') ADVANCE(73);
      if (lookahead == 'p') ADVANCE(74);
      if (lookahead == 'u') ADVANCE(94);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'a') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'a') ADVANCE(82);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'b') ADVANCE(101);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'c') ADVANCE(95);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'd') ADVANCE(78);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'e') ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'g') ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'g') ADVANCE(78);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'h') ADVANCE(80);
      if (lookahead == 'j') ADVANCE(79);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'i') ADVANCE(75);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'i') ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'i') ADVANCE(99);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'n') ADVANCE(83);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'n') ADVANCE(81);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'o') ADVANCE(77);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'o') ADVANCE(100);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'r') ADVANCE(84);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'r') ADVANCE(86);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 's') ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 's') ADVANCE(85);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 't') ADVANCE(106);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 't') ADVANCE(91);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 't') ADVANCE(78);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 't') ADVANCE(96);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 't') ADVANCE(93);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'u') ADVANCE(95);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'u') ADVANCE(97);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == 'y') ADVANCE(90);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == '-' ||
          lookahead == '.' ||
          lookahead == ':') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '>') ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == 'c') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'p') ADVANCE(7);
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '<') ADVANCE(63);
      if (lookahead == '@') ADVANCE(108);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '<') ADVANCE(64);
      if (lookahead == '@') ADVANCE(107);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(111);
      if (lookahead != 0) ADVANCE(112);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(112);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 44},
  [2] = {.lex_state = 44},
  [3] = {.lex_state = 44},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 44},
  [6] = {.lex_state = 44},
  [7] = {.lex_state = 44},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 44},
  [10] = {.lex_state = 44},
  [11] = {.lex_state = 44},
  [12] = {.lex_state = 44},
  [13] = {.lex_state = 44},
  [14] = {.lex_state = 44},
  [15] = {.lex_state = 44},
  [16] = {.lex_state = 44},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 44},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 39},
  [22] = {.lex_state = 39},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 39},
  [25] = {.lex_state = 39},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 39},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 39},
  [43] = {.lex_state = 39},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 40},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 41},
  [54] = {.lex_state = 42},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 42},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 41},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 41},
  [63] = {.lex_state = 41},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [anon_sym_ATpage] = ACTIONS(1),
    [anon_sym_ATusing] = ACTIONS(1),
    [anon_sym_ATinject] = ACTIONS(1),
    [anon_sym_ATlayout] = ACTIONS(1),
    [anon_sym_ATinherits] = ACTIONS(1),
    [anon_sym_ATattribute] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_ATcode] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_unquoted_value] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(57),
    [sym_directive] = STATE(2),
    [sym_code_block] = STATE(2),
    [sym_markup_element] = STATE(2),
    [sym_self_closing_markup_element] = STATE(2),
    [sym_tag_open] = STATE(4),
    [sym_self_closing_tag_open] = STATE(9),
    [sym_razor_expression] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_newline] = ACTIONS(5),
    [anon_sym_ATpage] = ACTIONS(7),
    [anon_sym_ATusing] = ACTIONS(9),
    [anon_sym_ATinject] = ACTIONS(9),
    [anon_sym_ATlayout] = ACTIONS(9),
    [anon_sym_ATinherits] = ACTIONS(9),
    [anon_sym_ATattribute] = ACTIONS(9),
    [anon_sym_ATcode] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_AT] = ACTIONS(15),
    [sym_text] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(7), 1,
      anon_sym_ATpage,
    ACTIONS(11), 1,
      anon_sym_ATcode,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_tag_open,
    STATE(9), 1,
      sym_self_closing_tag_open,
    ACTIONS(19), 2,
      sym_newline,
      sym_text,
    ACTIONS(9), 5,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
    STATE(3), 6,
      sym_directive,
      sym_code_block,
      sym_markup_element,
      sym_self_closing_markup_element,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [41] = 10,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      anon_sym_ATpage,
    ACTIONS(32), 1,
      anon_sym_ATcode,
    ACTIONS(35), 1,
      anon_sym_LT,
    ACTIONS(38), 1,
      anon_sym_AT,
    STATE(4), 1,
      sym_tag_open,
    STATE(9), 1,
      sym_self_closing_tag_open,
    ACTIONS(23), 2,
      sym_newline,
      sym_text,
    ACTIONS(29), 5,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
    STATE(3), 6,
      sym_directive,
      sym_code_block,
      sym_markup_element,
      sym_self_closing_markup_element,
      sym_razor_expression,
      aux_sym_source_file_repeat1,
  [82] = 8,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(47), 1,
      anon_sym_AT,
    STATE(7), 1,
      sym_tag_close,
    STATE(17), 1,
      sym_tag_open,
    STATE(26), 1,
      sym_self_closing_tag_open,
    ACTIONS(41), 2,
      sym_newline,
      sym_text,
    STATE(8), 4,
      sym_markup_element,
      sym_self_closing_markup_element,
      sym_razor_expression,
      aux_sym_markup_element_repeat1,
  [111] = 2,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [128] = 2,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [145] = 2,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [162] = 8,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    ACTIONS(47), 1,
      anon_sym_AT,
    STATE(14), 1,
      sym_tag_close,
    STATE(17), 1,
      sym_tag_open,
    STATE(26), 1,
      sym_self_closing_tag_open,
    ACTIONS(61), 2,
      sym_newline,
      sym_text,
    STATE(20), 4,
      sym_markup_element,
      sym_self_closing_markup_element,
      sym_razor_expression,
      aux_sym_markup_element_repeat1,
  [191] = 2,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [208] = 2,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(69), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [225] = 2,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [242] = 2,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [259] = 2,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [276] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [293] = 2,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [310] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [327] = 8,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(47), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_LT_SLASH,
    STATE(17), 1,
      sym_tag_open,
    STATE(26), 1,
      sym_self_closing_tag_open,
    STATE(30), 1,
      sym_tag_close,
    ACTIONS(95), 2,
      sym_newline,
      sym_text,
    STATE(19), 4,
      sym_markup_element,
      sym_self_closing_markup_element,
      sym_razor_expression,
      aux_sym_markup_element_repeat1,
  [356] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 11,
      sym_newline,
      anon_sym_ATpage,
      anon_sym_ATusing,
      anon_sym_ATinject,
      anon_sym_ATlayout,
      anon_sym_ATinherits,
      anon_sym_ATattribute,
      anon_sym_ATcode,
      anon_sym_LT,
      anon_sym_AT,
      sym_text,
  [373] = 8,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(47), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      anon_sym_LT_SLASH,
    STATE(17), 1,
      sym_tag_open,
    STATE(26), 1,
      sym_self_closing_tag_open,
    STATE(33), 1,
      sym_tag_close,
    ACTIONS(61), 2,
      sym_newline,
      sym_text,
    STATE(20), 4,
      sym_markup_element,
      sym_self_closing_markup_element,
      sym_razor_expression,
      aux_sym_markup_element_repeat1,
  [402] = 7,
    ACTIONS(106), 1,
      anon_sym_LT,
    ACTIONS(109), 1,
      anon_sym_LT_SLASH,
    ACTIONS(111), 1,
      anon_sym_AT,
    STATE(17), 1,
      sym_tag_open,
    STATE(26), 1,
      sym_self_closing_tag_open,
    ACTIONS(103), 2,
      sym_newline,
      sym_text,
    STATE(20), 4,
      sym_markup_element,
      sym_self_closing_markup_element,
      sym_razor_expression,
      aux_sym_markup_element_repeat1,
  [428] = 5,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 1,
      sym_csharp_text,
    STATE(58), 1,
      sym_csharp_code,
    STATE(22), 2,
      sym_csharp_block,
      aux_sym_csharp_code_repeat1,
  [445] = 4,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      sym_csharp_text,
    STATE(25), 2,
      sym_csharp_block,
      aux_sym_csharp_code_repeat1,
  [459] = 1,
    ACTIONS(124), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [467] = 4,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 1,
      sym_csharp_text,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    STATE(25), 2,
      sym_csharp_block,
      aux_sym_csharp_code_repeat1,
  [481] = 4,
    ACTIONS(128), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    ACTIONS(133), 1,
      sym_csharp_text,
    STATE(25), 2,
      sym_csharp_block,
      aux_sym_csharp_code_repeat1,
  [495] = 1,
    ACTIONS(65), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [503] = 3,
    ACTIONS(138), 1,
      sym_attribute_name,
    ACTIONS(136), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(27), 2,
      sym_attribute,
      aux_sym_tag_open_repeat1,
  [515] = 1,
    ACTIONS(141), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [523] = 1,
    ACTIONS(55), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [531] = 1,
    ACTIONS(59), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [539] = 4,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    ACTIONS(145), 1,
      sym_csharp_text,
    STATE(24), 2,
      sym_csharp_block,
      aux_sym_csharp_code_repeat1,
  [553] = 1,
    ACTIONS(77), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [561] = 1,
    ACTIONS(85), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [569] = 4,
    ACTIONS(147), 1,
      anon_sym_GT,
    ACTIONS(149), 1,
      anon_sym_SLASH_GT,
    ACTIONS(151), 1,
      sym_attribute_name,
    STATE(37), 2,
      sym_attribute,
      aux_sym_tag_open_repeat1,
  [583] = 1,
    ACTIONS(89), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [591] = 1,
    ACTIONS(93), 5,
      sym_newline,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      anon_sym_AT,
      sym_text,
  [599] = 4,
    ACTIONS(151), 1,
      sym_attribute_name,
    ACTIONS(153), 1,
      anon_sym_GT,
    ACTIONS(155), 1,
      anon_sym_SLASH_GT,
    STATE(27), 2,
      sym_attribute,
      aux_sym_tag_open_repeat1,
  [613] = 4,
    ACTIONS(147), 1,
      anon_sym_GT,
    ACTIONS(151), 1,
      sym_attribute_name,
    ACTIONS(157), 1,
      anon_sym_SLASH_GT,
    STATE(39), 2,
      sym_attribute,
      aux_sym_tag_open_repeat1,
  [627] = 4,
    ACTIONS(151), 1,
      sym_attribute_name,
    ACTIONS(153), 1,
      anon_sym_GT,
    ACTIONS(159), 1,
      anon_sym_SLASH_GT,
    STATE(27), 2,
      sym_attribute,
      aux_sym_tag_open_repeat1,
  [641] = 2,
    ACTIONS(163), 1,
      anon_sym_EQ,
    ACTIONS(161), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [650] = 3,
    ACTIONS(165), 1,
      anon_sym_DQUOTE,
    ACTIONS(167), 1,
      sym_unquoted_value,
    STATE(44), 1,
      sym_quoted_value,
  [660] = 1,
    ACTIONS(169), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_csharp_text,
  [666] = 1,
    ACTIONS(171), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_csharp_text,
  [672] = 1,
    ACTIONS(173), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [678] = 1,
    ACTIONS(67), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [684] = 1,
    ACTIONS(79), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [690] = 2,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      sym_quoted_value_content,
  [697] = 2,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    STATE(5), 1,
      sym_quoted_value,
  [704] = 2,
    ACTIONS(181), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_quoted_value_content,
  [711] = 1,
    ACTIONS(185), 1,
      sym_directive_value,
  [715] = 1,
    ACTIONS(187), 1,
      anon_sym_LBRACE,
  [719] = 1,
    ACTIONS(189), 1,
      anon_sym_GT,
  [723] = 1,
    ACTIONS(191), 1,
      sym_tag_name,
  [727] = 1,
    ACTIONS(193), 1,
      sym_identifier,
  [731] = 1,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
  [735] = 1,
    ACTIONS(197), 1,
      sym_identifier,
  [739] = 1,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
  [743] = 1,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
  [747] = 1,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
  [751] = 1,
    ACTIONS(205), 1,
      sym_tag_name,
  [755] = 1,
    ACTIONS(207), 1,
      anon_sym_GT,
  [759] = 1,
    ACTIONS(209), 1,
      sym_tag_name,
  [763] = 1,
    ACTIONS(211), 1,
      sym_tag_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 128,
  [SMALL_STATE(7)] = 145,
  [SMALL_STATE(8)] = 162,
  [SMALL_STATE(9)] = 191,
  [SMALL_STATE(10)] = 208,
  [SMALL_STATE(11)] = 225,
  [SMALL_STATE(12)] = 242,
  [SMALL_STATE(13)] = 259,
  [SMALL_STATE(14)] = 276,
  [SMALL_STATE(15)] = 293,
  [SMALL_STATE(16)] = 310,
  [SMALL_STATE(17)] = 327,
  [SMALL_STATE(18)] = 356,
  [SMALL_STATE(19)] = 373,
  [SMALL_STATE(20)] = 402,
  [SMALL_STATE(21)] = 428,
  [SMALL_STATE(22)] = 445,
  [SMALL_STATE(23)] = 459,
  [SMALL_STATE(24)] = 467,
  [SMALL_STATE(25)] = 481,
  [SMALL_STATE(26)] = 495,
  [SMALL_STATE(27)] = 503,
  [SMALL_STATE(28)] = 515,
  [SMALL_STATE(29)] = 523,
  [SMALL_STATE(30)] = 531,
  [SMALL_STATE(31)] = 539,
  [SMALL_STATE(32)] = 553,
  [SMALL_STATE(33)] = 561,
  [SMALL_STATE(34)] = 569,
  [SMALL_STATE(35)] = 583,
  [SMALL_STATE(36)] = 591,
  [SMALL_STATE(37)] = 599,
  [SMALL_STATE(38)] = 613,
  [SMALL_STATE(39)] = 627,
  [SMALL_STATE(40)] = 641,
  [SMALL_STATE(41)] = 650,
  [SMALL_STATE(42)] = 660,
  [SMALL_STATE(43)] = 666,
  [SMALL_STATE(44)] = 672,
  [SMALL_STATE(45)] = 678,
  [SMALL_STATE(46)] = 684,
  [SMALL_STATE(47)] = 690,
  [SMALL_STATE(48)] = 697,
  [SMALL_STATE(49)] = 704,
  [SMALL_STATE(50)] = 711,
  [SMALL_STATE(51)] = 715,
  [SMALL_STATE(52)] = 719,
  [SMALL_STATE(53)] = 723,
  [SMALL_STATE(54)] = 727,
  [SMALL_STATE(55)] = 731,
  [SMALL_STATE(56)] = 735,
  [SMALL_STATE(57)] = 739,
  [SMALL_STATE(58)] = 743,
  [SMALL_STATE(59)] = 747,
  [SMALL_STATE(60)] = 751,
  [SMALL_STATE(61)] = 755,
  [SMALL_STATE(62)] = 759,
  [SMALL_STATE(63)] = 763,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 2, 0, 2),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 2, 0, 2),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_razor_expression, 2, 0, 3),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_razor_expression, 2, 0, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_element, 2, 0, 4),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_element, 2, 0, 4),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_markup_element, 1, 0, 1),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_markup_element, 1, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_value, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_value, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag_open, 3, 0, 3),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag_open, 3, 0, 3),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_value, 3, 0, 7),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_value, 3, 0, 7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_element, 3, 0, 6),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_element, 3, 0, 6),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag_open, 4, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag_open, 4, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_close, 3, 0, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_close, 3, 0, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 4, 0, 8),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 4, 0, 8),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_element_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_element_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_markup_element_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_element_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_csharp_code, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 4, 0, 3),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_csharp_code_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_csharp_code_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_csharp_code_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_open_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_open_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 3, 0, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 5),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_csharp_block, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_csharp_block, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 9),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [199] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_razor(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "razor",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
